### ISSUE TITLE
1.20.1 Version for Modpacks

### ISSUE THREAD

**Issue by TheGamerCailo** [Traben-0/stuck_arrows_for_all#2]
I think for modding, 1.20.1 version slightly has an edge over 1.21 version. A lot of other mod authors still have not updated to 1.21, which makes it difficult for my modpack when I find good mods that are only for 1.21. Your mod is a great one, and I'm particularly hung up on it cuz it was really the only one that I saw that added this feature. (There was one other but it was very buggy and only for forge).

If you could add support for 1.20.1, the version of my modpack, that would be GREAT! Thanks!

**Comment by Traben-0** [comment]
duplciate #1
